# ============================================================
# agent_sar.py
# FinCrime Multi-Agent System — SAR Agent (Ephemeral)
# ============================================================
# Data collection is hardcoded and reliable.
# Only the SAR narrative generation code is ephemeral —
# generated by LLM, executed, then deleted.
#
# Ephemeral pattern:
#   1. Hardcoded SQL queries → collect all data reliably
#   2. Score alert + identify red flags
#   3. LLM generates SAR narrative prompt code → execute
#   4. DELETE generated narrative code
#   5. Return SAR result
# ============================================================

import os
import re
import traceback
from datetime import datetime
from orchestrator import call_llm, get_token, GATEWAY, MODEL
from multi_agent_state import AgentState
from databricks import sql as dbsql


# ── FATF lists ────────────────────────────────────────────
FATF_GREY  = [
    "BF","CM","CG","CI","HR","ET","HT","KE","LB","ML",
    "MZ","NA","NG","PH","SA","SN","SS","SY","TZ","TT",
    "VN","VU","YE"
]
FATF_BLACK = ["KP","IR","MM"]


# ── SQL connector ─────────────────────────────────────────
def get_connection():
    from setup import DATABRICKS_HOST, DATABRICKS_TOKEN, DATABRICKS_HTTP_PATH
    return dbsql.connect(
        server_hostname = DATABRICKS_HOST,
        http_path       = DATABRICKS_HTTP_PATH,
        access_token    = DATABRICKS_TOKEN,
    )


def run_sql(sql: str) -> list:
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(sql.strip())
            if cursor.description is None:
                return []
            cols = [d[0] for d in cursor.description]
            return [dict(zip(cols, row)) for row in cursor.fetchall()]


def run_sql_one(sql: str) -> dict:
    results = run_sql(sql)
    return results[0] if results else {}


# ── agent_sar() ───────────────────────────────────────────
def agent_sar(state: AgentState) -> AgentState:
    """
    SAR Agent — reliable data collection + ephemeral narrative.
    Data queries are hardcoded for reliability.
    Only the SAR narrative generation code is ephemeral.
    """

    message  = state["current_input"]
    alert_id = state.get("sar_alert_id")

    # Extract alert ID from message if not set
    if not alert_id:
        match = re.search(r'ALT-\d{4}-\d{5}', message, re.IGNORECASE)
        if match:
            alert_id = match.group(0).upper()

    if not alert_id:
        return {
            **state,
            "final_response": (
                "Please provide an Alert ID to investigate.\n"
                "Format: ALT-YYYY-NNNNN\n"
                "Example: ALT-2024-08821"
            ),
            "response_type": "text",
            "error":         "No alert ID provided",
        }

    print(f"\n📝 [SAR Agent] Investigating: {alert_id}")

    # ══════════════════════════════════════════════════════
    # STEP 1 — Collect all data via hardcoded SQL queries
    # ══════════════════════════════════════════════════════
    print(f"   Step 1: Collecting alert data...")

    # 1a. Fetch alert
    alert = run_sql_one(f"""
        SELECT alert_id, customer_id, account_id, rule_name,
               alert_type, alert_subtype, risk_score, risk_tier,
               total_amount, transaction_count, period_start,
               period_end, detected_at, status, notes
        FROM silver.alerts
        WHERE alert_id = '{alert_id}'
    """)

    if not alert:
        return {
            **state,
            "final_response": f"Alert {alert_id} not found in silver.alerts.",
            "response_type":  "text",
            "error":          f"Alert {alert_id} not found",
        }

    customer_id = alert.get("customer_id", "")
    account_id  = alert.get("account_id", "")
    print(f"   Alert found — customer: {customer_id}")

    # 1b. Fetch customer
    customer = run_sql_one(f"""
        SELECT customer_id, full_name, dob, occupation, employer,
               industry, annual_income, address, state,
               customer_since, kyc_tier, kyc_last_review,
               risk_rating, pep_flag, fatca_flag
        FROM silver.customers
        WHERE customer_id = '{customer_id}'
    """)
    print(f"   Customer: {customer.get('full_name','—')}")

    # 1c. Fetch account
    account = run_sql_one(f"""
        SELECT account_id, bsb, account_number, account_type,
               avg_monthly_credit, avg_monthly_debit
        FROM silver.accounts
        WHERE account_id = '{account_id}'
    """)

    # 1d. Fetch transactions
    transactions = run_sql(f"""
        SELECT txn_id, txn_date, amount, channel, direction,
               branch, counterparty_country, counterparty_id,
               counterparty_bank, reference
        FROM silver.transactions
        WHERE alert_id = '{alert_id}'
        ORDER BY txn_date
    """)
    print(f"   Transactions: {len(transactions)}")

    # 1e. Fetch prior alert history
    prior_alerts = run_sql(f"""
        SELECT alert_id, alert_date, alert_type, risk_score,
               disposition, sar_filed
        FROM silver.alert_history
        WHERE customer_id = '{customer_id}'
          AND alert_id != '{alert_id}'
          AND disposition != 'IN_PROGRESS'
        ORDER BY alert_date DESC
    """)
    print(f"   Prior alerts: {len(prior_alerts)}")

    # 1f. Fetch counterparties
    counterparty_ids = list(set(
        t.get("counterparty_id","")
        for t in transactions
        if t.get("counterparty_id")
    ))
    counterparties = []
    if counterparty_ids:
        id_list = "','".join(counterparty_ids)
        counterparties = run_sql(f"""
            SELECT counterparty_id, name, bank_name, bank_country,
                   fatf_status, flagged, relationship_to_cust
            FROM silver.counterparties
            WHERE counterparty_id IN ('{id_list}')
        """)
    print(f"   Counterparties: {len(counterparties)}")

    # ══════════════════════════════════════════════════════
    # STEP 2 — Score alert and identify red flags
    # ══════════════════════════════════════════════════════
    print(f"   Step 2: Scoring alert...")

    base_score  = int(alert.get("risk_score") or 50)
    adjustment  = 0
    red_flags   = []
    txn_count   = len(transactions) or int(alert.get("transaction_count") or 0)
    total_amt   = float(alert.get("total_amount") or 0)
    annual_inc  = float(customer.get("annual_income") or 0)
    risk_rating = str(customer.get("risk_rating") or "").upper()
    kyc_tier    = str(customer.get("kyc_tier") or "").upper()

    # Structuring pattern
    if txn_count >= 3:
        red_flags.append(
            f"{txn_count} cash deposits totalling AUD ${total_amt:,.2f} "
            f"— consistent with structuring to avoid AUSTRAC $10,000 CTF threshold"
        )

    # Multi-branch
    cash_txns = [t for t in transactions if t.get("channel") == "CASH_DEPOSIT"]
    branches  = list(set(t.get("branch","") for t in cash_txns if t.get("branch")))
    if len(branches) >= 3:
        red_flags.append(
            f"Cash deposits spread across {len(branches)} branches "
            f"({', '.join(branches)}) — deliberate threshold avoidance"
        )

    # Offshore wire
    offshore = list(set(
        t.get("counterparty_country","")
        for t in transactions
        if t.get("channel") == "SWIFT_OUTWARD"
        and t.get("counterparty_country","") not in ("AU","","None")
    ))
    if offshore:
        adjustment += 5
        red_flags.append(
            f"Outward SWIFT wire to {', '.join(offshore)} "
            f"following cash accumulation — placement to layering pattern"
        )

    # FATF hits
    all_countries = [
        t.get("counterparty_country","") for t in transactions
        if t.get("counterparty_country","") not in ("","None")
    ]
    fatf_hits = list(set(c for c in all_countries if c in FATF_GREY + FATF_BLACK))
    if fatf_hits:
        adjustment += 5
        for country in fatf_hits:
            list_type = "BLACK LIST" if country in FATF_BLACK else "GREY LIST"
            red_flags.append(
                f"Destination country '{country}' on FATF {list_type} "
                f"— elevated money laundering risk jurisdiction"
            )

    # Flagged counterparties
    flagged_entities = [
        c.get("name","") for c in counterparties if c.get("flagged")
    ]
    if flagged_entities:
        adjustment += 5
        red_flags.append(
            f"Flagged counterparty identified: {', '.join(flagged_entities)} "
            f"— no verifiable legitimate business purpose"
        )

    # Customer risk profile
    if risk_rating == "HIGH":
        red_flags.append(
            "Customer carries HIGH internal risk rating "
            "— heightened scrutiny required under CDD obligations"
        )
    if kyc_tier == "ENHANCED":
        red_flags.append(
            f"Customer subject to Enhanced Due Diligence (EDD) "
            f"— KYC last reviewed {customer.get('kyc_last_review','—')}"
        )

    # Income inconsistency
    if annual_inc > 0 and total_amt > 0:
        monthly_inc = annual_inc / 12
        ratio = total_amt / monthly_inc
        if ratio > 5:
            red_flags.append(
                f"Transaction total AUD ${total_amt:,.2f} is {ratio:.1f}x "
                f"the customer's estimated monthly income of AUD ${monthly_inc:,.2f} "
                f"— grossly inconsistent with declared financial profile"
            )

    # Prior alerts same typology
    same_typology = [
        p for p in prior_alerts
        if p.get("alert_type") == alert.get("alert_type")
    ]
    if same_typology:
        adjustment += 5
        red_flags.append(
            f"Customer has {len(prior_alerts)} prior alert(s) — "
            f"same typology previously closed as false positive; "
            f"escalated scrutiny warranted"
        )

    # Adjustments
    if not offshore and not fatf_hits:
        adjustment -= 3
    if not prior_alerts:
        adjustment -= 2

    agent_score = max(0, min(100, base_score + adjustment))

    # Routing decision
    if agent_score >= 80 or any(c in FATF_BLACK for c in all_countries):
        routing = "SAR_DRAFT"
    elif agent_score >= 60:
        routing = "ESCALATE"
    else:
        routing = "AUTO_CLOSE"

    print(f"   Score: {agent_score}/100 → {routing}")
    print(f"   Red flags: {len(red_flags)}")

    # ── Non-SAR routing — return directly ─────────────────
    if routing != "SAR_DRAFT":
        verdict = {
            "ESCALATE": (
                f"📤 ESCALATED TO L2\n\n"
                f"Alert: {alert_id}\n"
                f"Customer: {customer.get('full_name','—')}\n"
                f"Risk Score: {agent_score}/100\n\n"
                f"Red Flags ({len(red_flags)}):\n" +
                "\n".join(f"• {f}" for f in red_flags)
            ),
            "AUTO_CLOSE": (
                f"✅ AUTO CLOSED\n\n"
                f"Alert: {alert_id}\n"
                f"Customer: {customer.get('full_name','—')}\n"
                f"Risk Score: {agent_score}/100\n\n"
                f"Insufficient indicators for SAR filing."
            ),
        }
        return {
            **state,
            "sar_result": {
                "alert_id":          alert_id,
                "customer_name":     customer.get("full_name","—"),
                "agent_risk_score":  agent_score,
                "routing_decision":  routing,
                "red_flags":         red_flags,
                "transaction_count": txn_count,
                "total_amount":      total_amt,
                "sar_narrative":     None,
            },
            "final_response": verdict.get(routing, f"Decision: {routing}"),
            "response_type":  "sar",
            "error":          None,
        }

    # ══════════════════════════════════════════════════════
    # STEP 3 — Generate SAR narrative (EPHEMERAL)
    # ══════════════════════════════════════════════════════
    print(f"   Step 3: Generating SAR narrative (ephemeral)...")

    # Format transaction table
    txn_lines = "\n".join(
        f"  {str(t.get('txn_date',''))[-10:]}  "
        f"{'↓ IN ' if t.get('direction')=='CREDIT' else '↑ OUT'}  "
        f"AUD ${float(t.get('amount',0)):>12,.2f}  "
        f"{str(t.get('channel','')):<22}  "
        f"{t.get('branch','')}"
        for t in transactions
    ) or "  No transaction detail available"

    flags_text = "\n".join(
        f"  {i+1}. {f}" for i, f in enumerate(red_flags)
    )

    cpty_text = "\n".join(
        f"  - {c.get('name','—')} | {c.get('bank_name','—')} "
        f"({c.get('bank_country','—')}) | FATF: {c.get('fatf_status','—')} "
        f"| Flagged: {c.get('flagged',False)}"
        for c in counterparties
    ) or "  No counterparty details available"

    prior_text = "\n".join(
        f"  - {str(p.get('alert_date',''))}  {p.get('alert_type','')}  "
        f"Risk:{p.get('risk_score','')}  → {p.get('disposition','')}"
        for p in prior_alerts
    ) or "  No prior alert history"

    # Build the full SAR prompt directly (no code generation needed)
    sar_prompt = f"""You are a senior AML/CTF compliance officer at Commonwealth Bank of Australia (CBA).
Draft a formal Suspicious Matter Report (SMR) for submission to AUSTRAC under the Anti-Money Laundering and Counter-Terrorism Financing Act 2006.

Use precise, formal compliance language. Be specific with all dates, amounts, branches, and entity names provided. Do not use vague language. Do not write "not available" — use only the data provided below.

═══════════════════════════════════════════════
ALERT INTELLIGENCE
═══════════════════════════════════════════════
Alert ID:         {alert_id}
Rule:             {alert.get('rule_name','—')}
Alert Type:       {alert.get('alert_type','—')} — {alert.get('alert_subtype','—')}
TM Risk Score:    {alert.get('risk_score','—')}/100
Agent Risk Score: {agent_score}/100
Risk Tier:        {alert.get('risk_tier','—')}
Detected:         {alert.get('detected_at','—')}

═══════════════════════════════════════════════
SUBJECT / CUSTOMER
═══════════════════════════════════════════════
Full Name:        {customer.get('full_name','—')}
Date of Birth:    {customer.get('dob','—')}
Occupation:       {customer.get('occupation','—')} at {customer.get('employer','—')}
Industry:         {customer.get('industry','—')}
Declared Income:  AUD ${annual_inc:,.2f} per annum
Address:          {customer.get('address','—')}
Customer Since:   {customer.get('customer_since','—')}
KYC Tier:         {kyc_tier} (last reviewed: {customer.get('kyc_last_review','—')})
Internal Rating:  {risk_rating}
PEP Flag:         {customer.get('pep_flag','—')}
Account:          BSB {account.get('bsb','—')} / {account.get('account_number','—')} ({account.get('account_type','—')})
Avg Monthly Credit: AUD ${float(account.get('avg_monthly_credit') or 0):,.2f}
Avg Monthly Debit:  AUD ${float(account.get('avg_monthly_debit') or 0):,.2f}

═══════════════════════════════════════════════
TRANSACTION ACTIVITY
═══════════════════════════════════════════════
Period:             {alert.get('period_start','—')} to {alert.get('period_end','—')}
Total Amount:       AUD ${total_amt:,.2f}
Transaction Count:  {txn_count}
Branches Used:      {', '.join(branches) if branches else '—'}
Offshore Wire:      {bool(offshore)}
Destinations:       {', '.join(offshore) if offshore else 'None'}

Transaction Detail:
{txn_lines}

═══════════════════════════════════════════════
COUNTERPARTIES
═══════════════════════════════════════════════
{cpty_text}

FATF Jurisdiction Hits: {', '.join(fatf_hits) if fatf_hits else 'None'}
Flagged Entities:       {', '.join(flagged_entities) if flagged_entities else 'None'}

═══════════════════════════════════════════════
PRIOR ALERT HISTORY
═══════════════════════════════════════════════
Prior Alert Count:  {len(prior_alerts)}
{prior_text}

═══════════════════════════════════════════════
AGENT RED FLAGS ({len(red_flags)} identified)
═══════════════════════════════════════════════
{flags_text}
═══════════════════════════════════════════════

Write the complete SMR narrative with EXACTLY these five sections:

1. BACKGROUND AND CUSTOMER PROFILE
2. DESCRIPTION OF SUSPICIOUS ACTIVITY
3. INDICATORS OF SUSPICIOUS BEHAVIOUR
4. TYPOLOGY AND REGULATORY ANALYSIS
5. RECOMMENDATION AND PROPOSED NEXT STEPS"""

    # ── Generate ephemeral narrative code ─────────────────
    # The code simply calls the LLM with the prompt above
    generated_narrative_code = f"""
import requests as _req
_token  = get_token()
_resp   = _req.post(
    GATEWAY,
    headers={{"Authorization": f"Bearer {{_token}}", "Content-Type": "application/json"}},
    json={{"model": MODEL, "max_tokens": 4000, "messages": [{{"role": "user", "content": _sar_prompt}}]}},
    timeout=120
)
if _resp.status_code == 200:
    sar_narrative = _resp.json()["choices"][0]["message"]["content"].strip()
else:
    sar_narrative = f"Gateway error {{_resp.status_code}}: {{_resp.text[:200]}}"
"""

    # Execute the generated code
    sar_narrative = None
    try:
        exec_scope = {
            "get_token":      get_token,
            "GATEWAY":        GATEWAY,
            "MODEL":          MODEL,
            "_sar_prompt":    sar_prompt,
            "sar_narrative":  None,
        }
        exec(generated_narrative_code, exec_scope)
        sar_narrative = exec_scope.get("sar_narrative")
        print(f"   SAR narrative: {len((sar_narrative or '').split())} words")
    except Exception as e:
        print(f"   ⚠️ Exec failed, calling LLM directly: {e}")
        # Fallback — call directly
        try:
            import requests
            token = get_token()
            resp  = requests.post(
                GATEWAY,
                headers={"Authorization": f"Bearer {token}",
                         "Content-Type":  "application/json"},
                json={"model": MODEL, "max_tokens": 4000,
                      "messages": [{"role": "user", "content": sar_prompt}]},
                timeout=120
            )
            if resp.status_code == 200:
                sar_narrative = resp.json()["choices"][0]["message"]["content"].strip()
        except Exception as e2:
            sar_narrative = f"SAR generation failed: {str(e2)}"

    # ── DELETE all generated code ─────────────────────────
    print(f"   Deleting generated narrative code (ephemeral)...")
    del generated_narrative_code
    del sar_prompt
    generated_narrative_code = None
    sar_prompt = None
    print(f"   ✅ All generated code deleted — no trace remains")

    # ══════════════════════════════════════════════════════
    # STEP 4 — Build and return result
    # ══════════════════════════════════════════════════════
    sar_ref   = f"SMR-{alert_id}"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    sar_result = {
        "alert_id":             alert_id,
        "customer_name":        customer.get("full_name","—"),
        "customer_id":          customer_id,
        "agent_risk_score":     agent_score,
        "routing_decision":     routing,
        "red_flags":            red_flags,
        "transaction_count":    txn_count,
        "total_amount":         total_amt,
        "sar_narrative":        sar_narrative,
        "sar_reference":        sar_ref,
        "draft_timestamp":      timestamp,
        "model_used":           MODEL,
        "fatf_hits":            fatf_hits,
        "offshore_destinations":offshore,
        "branches_used":        branches,
        "counterparties":       counterparties,
    }

    summary = (
        f"⚡ SAR DRAFTED — {sar_ref}\n\n"
        f"Customer: {customer.get('full_name','—')}\n"
        f"Risk Score: {agent_score}/100\n"
        f"Red Flags: {len(red_flags)}\n"
        f"Transactions: {txn_count} totalling AUD ${total_amt:,.2f}\n"
        f"Decision: {routing}\n\n"
        f"🔒 All generated code deleted after execution."
    )

    print(f"✅ [SAR Agent] Complete — {sar_ref}")

    return {
        **state,
        "sar_result":     sar_result,
        "sar_alert_id":   alert_id,
        "final_response": summary,
        "response_type":  "sar",
        "error":          None,
    }